config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin
  resources :pages do
    member do
      post :load
      post :create_wikidata
    end
  end

  # Frontend
  resources :statements, only: %i[index show] do
    collection do
      get 'statistics'
    end
  end
  resources :verifications, only: %i[create]
  resources :reconciliations, only: %i[create]

  match '/api-proxy' => 'media_wiki_api#api_proxy', :via => %i[get post]

  get 'wikidata-page-setup', to: 'wikidata_page#setup'

  get 'frontend', to: 'general#frontend'
  root 'general#index'
end

app/models/statement.rb
# frozen_string_literal: true

# Statement for verification object
class Statement < ApplicationRecord
  scope :original, -> { where(duplicate: false) }

  belongs_to :page
  has_many :verifications, dependent: :destroy
  has_many :reconciliations, dependent: :destroy

  validates :transaction_id, presence: true, uniqueness: true

  before_create :detect_duplicate_statements, :retrieve_wikidata_id
  after_create :verify_duplicate!, if: :duplicate?

  delegate :parliamentary_term_item, :parliamentary_term_name, to: :page

  def latest_verification
    verifications.last
  end

  def latest_reconciliation
    reconciliations.last
  end

  def record_actioned!(classifier_version = nil)
    self.actioned_at = Time.zone.now
    self.classifier_version = classifier_version.sub(/^v/, '') if classifier_version
    save!
  end

  def report_error!(error_message)
    self.error_reported = error_message
    self.reported_at = Time.zone.now
    save!
  end

  def clear_error!
    self.error_reported = nil
    self.reported_at = nil
    save!
  end

  def self_and_duplicate_statements
    Statement.where(
      page:                     page,
      person_name:              person_name,
      electoral_district_name:  electoral_district_name,
      electoral_district_item:  electoral_district_item,
      parliamentary_group_item: parliamentary_group_item,
      parliamentary_group_name: parliamentary_group_name,
      position_start:           position_start,
      position_end:             position_end,
      fb_identifier:            fb_identifier,
      removed_from_source:      false
    )
  end

  def duplicate_statements
    self_and_duplicate_statements.where.not(id: id).order(created_at: :asc)
  end

  delegate :from_suggestions_store?, to: :page

  private

  def detect_duplicate_statements
    self.duplicate ||= duplicate_statements.present?
  end

  def verify_duplicate!
    duplicate_verification = duplicate_statements.last.latest_verification
    return unless duplicate_verification

    verifications.create!(
      user:          duplicate_verification.user,
      status:        duplicate_verification.status,
      reference_url: duplicate_verification.reference_url
    )
  end

  def retrieve_wikidata_id
    self.person_item ||= store.wikidata_id
  end

  def store
    IDMappingStore.new(wikidata_id: person_item, facebook_id: fb_identifier)
  end
end

app/controllers/statements_controller.rb
# frozen_string_literal: true

class StatementsController < FrontendController
  def index
    page = Page.find_by!(title: params.require(:title))
    @classifier = classify_page(page)

    respond_to do |format|
      format.json { render }
    end
  end

  def statistics
    @country_statements = StatementsStatistics.new.statistics
    @country_lookup = Page.select(:country_code, :country_name).distinct.each_with_object({}) do |p, memo|
      memo[p.country_code] ||= p.country_name
    end
    positions = @country_statements.values.map(&:first).flatten.map(&:position)
    @position_name_mapping = RetrieveItems.run(*positions)
  end

  def show
    statement = Statement.find_by!(transaction_id: params.fetch(:id))

    case params[:force_type]
    when 'done'
      statement.record_actioned!(PageClassifier::VERSION)
    when 'manually_actionable'
      statement.report_error!(params[:error_message])
    when 'actionable'
      statement.clear_error!
    end

    respond_with(statement)
  end
end

app/views/statements/statistics.html.erb
<% @country_statements.each do |country_code, (statements, invalid_statements)| %>
  <h2>
    <% if country = @country_lookup[country_code.downcase] %>
      <%= country %>
    <% else %>
      <%= country_code %>
    <% end %>
  </h2>
  <table class="wikitable">
    <thead>
      <tr>
        <th>Wikidata position</th>
        <th>Page</th>
        <th>Unchecked</th>
        <th>Correct</th>
        <th>Incorrect</th>
      </tr>
    </thead>
    <tbody>
      <% statements.each do |statement| %>
      <tr>
        <td>
          <%= link_to "https://www.wikidata.org/wiki/#{statement.position}" do %>
            <%= @position_name_mapping[statement.position]&.label %>
            <small>(<%= statement.position %>)</small>
          <% end %>
        </td>
        <td><% if statement.pages.each do |page_title| %>
          <a href="https://www.wikidata.org/wiki/<%= page_title %>"><%= page_title %></a>
          <% end.empty? %>
          missing (<%= link_to 'Create page', new_page_path(
            title: "User:Verification_pages_bot/verification/#{country_code.downcase}/",
            position_held_item: statement.position,
            csv_source_url: SuggestionsStore::Country.new(code: country_code.downcase).export_position_url(position: statement.position, format: 'csv')
          ) %>)
        <% end %></td>
        <td><%= statement.unchecked %></td>
        <td><%= statement.correct %></td>
        <td><%= statement.incorrect %></td>
      </tr>
    <% end %>
    <% if invalid_statements.count > 0 %>
    <tr>
      <td colspan="5">
        <details>
          <summary>Invalid statements: <%= invalid_statements.count %></summary>

          <table class="wikitable">
            <tr>
              <th>Transaction ID</th>
              <th>Electoral District</th>
              <th>Role code</th>
            </tr>
            <% invalid_statements.each do |statement| %>
            <tr>
              <td><%= statement['transaction_id'] %></td>
              <td><a href="https://www.wikidata.org/wiki/<%= statement['electoral_district_item'] %>"><%= statement['electoral_district_item'] %></a></td>
              <td><%= statement['role_code'] %></td>
            </tr>
            <% end %>
          </table>
        </details>
      </td>
    </tr>
    <% end %>
    </tbody>
  </table>
<% end %>