config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin
  resources :pages do
    member do
      post :load
      post :create_wikidata
    end
  end

  # Frontend
  resources :statements, only: %i[index show] do
    collection do
      get 'statistics'
    end
  end
  resources :verifications, only: %i[create]
  resources :reconciliations, only: %i[create]

  match '/api-proxy' => 'media_wiki_api#api_proxy', :via => %i[get post]

  get 'wikidata-page-setup', to: 'wikidata_page#setup'

  get 'frontend', to: 'general#frontend'
  root 'general#index'
end

app/views/pages/_form.html.erb
<%= form_for @page, html: { class: "form-horizontal page" } do |f| %>

  <% if @page.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@page.errors.count, "error") %> prohibited this page from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @page.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :title, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :title, class: 'form-control' %>
    </div>
    <%= f.error_span(:title) %>
  </div>
  <div class="form-group">
    <%= f.label :position_held_item, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :position_held_item, class: 'form-control' %>
    </div>
    <%= f.error_span(:position_held_item) %>
  </div>
  <div class="form-group">
    <%= f.label :parliamentary_term_item, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :parliamentary_term_item, class: 'form-control' %>
    </div>
    <%= f.error_span(:parliamentary_term_item) %>
  </div>
  <div class="form-group">
    <%= f.label :country_item, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :country_item, class: 'form-control' %>
    </div>
    <%= f.error_span(:country_item) %>
  </div>
  <% if @page.hash_epoch <= 2 %>
  <div class="form-group">
    <%= f.label :country_code, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :country_code, class: 'form-control' %>
    </div>
    <%= f.error_span(:country_code) %>
  </div>
  <% end %>
  <div class="form-group">
    <%= f.label :reference_url, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reference_url, class: 'form-control' %>
    </div>
    <%= f.error_span(:reference_url) %>
  </div>
  <div class="form-group">
    <%= f.label :new_item_description_en, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :new_item_description_en, class: 'form-control' %>
    </div>
    <%= f.error_span(:new_item_description_en) %>
  </div>
  <div class="form-group">
    <%= f.label :new_party_description_en, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :new_party_description_en, class: 'form-control' %>
    </div>
    <%= f.error_span(:new_party_description_en) %>
  </div>
  <div class="form-group">
    <%= f.label :new_party_instance_of_item, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :new_party_instance_of_item, class: 'form-control' %>
    </div>
    <%= f.error_span(:new_party_instance_of_item) %>
  </div>
  <div class="form-group">
    <%= f.label :new_district_description_en, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :new_district_description_en, class: 'form-control' %>
    </div>
    <%= f.error_span(:new_district_description_en) %>
  </div>
  <div class="form-group">
    <%= f.label :new_district_instance_of_item, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :new_district_instance_of_item, class: 'form-control' %>
    </div>
    <%= f.error_span(:new_district_instance_of_item) %>
  </div>
  <!--
  <div class="form-group">
    <%= f.label :reference_url_title, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reference_url_title, class: 'form-control' %>
    </div>
    <%= f.error_span(:reference_url_title) %>
  </div>
  <div class="form-group">
    <%= f.label :reference_url_language, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :reference_url_language, class: 'form-control' %>
    </div>
    <%= f.error_span(:reference_url_language) %>
  </div>
  -->
  <div class="form-group">
    <%= f.label :csv_source_url, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :csv_source_url, class: 'form-control' %>
    </div>
    <%= f.error_span(:csv_source_url) %>
  </div>
  <div class="form-group">
    <%= f.label :csv_source_language, class: 'control-label col-lg-2' %>
    <div class="col-lg-10">
      <%= f.text_field :csv_source_language, class: 'form-control' %>
    </div>
    <%= f.error_span(:csv_source_language) %>
  </div>
  <div class="form-check">
    <%= f.check_box :executive_position %>
    <%= f.label :executive_position, class: 'form-check-label' %>
    <%= f.error_span(:executive_position) %>
  </div>
  <div class="form-check">
    <%= f.check_box :archived %>
    <%= f.label :archived, class: 'form-check-label' %>
    <%= f.error_span(:archived) %>
  </div>

  <div class="form-group">
    <div class="col-lg-offset-2 col-lg-10">
      <%= f.submit nil, class: 'btn btn-primary' %>
      <%= link_to t('.cancel', default: t("helpers.links.cancel")),
                pages_path, class: 'btn btn-default' %>
    </div>
  </div>

<% end %>

app/views/pages/edit.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%= t '.title', default: [:'helpers.titles.edit', 'Edit %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/pages/index.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%= t '.title', default: model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:title) %></th>
      <th><%= model_class.human_attribute_name(:position_held_item) %></th>
      <th><%= model_class.human_attribute_name(:parliamentary_term_item) %></th>
      <th><%= model_class.human_attribute_name(:country_item) %></th>
      <th><%= model_class.human_attribute_name(:executive_position) %></th>
      <th><%= model_class.human_attribute_name(:archived) %></th>
      <th><%= t '.actions', default: t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= link_to page.id, page_path(page) %></td>
        <td class="title"><%= link_to_wiki page.title %></td>
        <td><%= link_to_wiki page.position_held_name, page.position_held_item %></td>
        <td><%= link_to_wiki page.parliamentary_term_name, page.parliamentary_term_item %></td>
        <td><%= link_to_wiki page.country_name, page.country_item %></td>
        <td><%= page.executive_position %></td>
        <td><%= page.archived %></td>
        <td>
          <%= link_to t('.show', default: t("helpers.links.show")),
                      page_path(page), class: 'btn btn-default btn-xs' %>
          <%= link_to t('.edit', default: t("helpers.links.edit")),
                      edit_page_path(page), class: 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', default: t("helpers.links.destroy")),
                      page_path(page),
                      method: :delete,
                      data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
                      class: 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', default: t("helpers.links.new")),
            new_page_path,
            class: 'btn btn-primary' %>

app/views/pages/new.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%= t '.title', default: [:'helpers.titles.new', 'New %{model}'], model: model_class.model_name.human.titleize %></h1>
</div>
<%= render partial: 'form' %>

app/views/pages/show.html.erb
<%- model_class = Page -%>
<div class="page-header">
  <h1><%= t '.title', default: model_class.model_name.human.titleize %></h1>
</div>

<% if @page.archived? %>
  <p class="alert alert-warning">This page has been archived.</p>
<% end %>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:title) %>:</strong></dt>
  <dd><%= link_to_wiki @page.title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:position_held_item) %>:</strong></dt>
  <dd><%= link_to_wiki @page.position_held_name, @page.position_held_item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:parliamentary_term_item) %>:</strong></dt>
  <dd><%= link_to_wiki @page.parliamentary_term_name, @page.parliamentary_term_item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:country_item) %>:</strong></dt>
  <dd><%= link_to_wiki @page.country_name, @page.country_item %></dd>
  <% if @page.hash_epoch <= 2 %>
  <dt><strong><%= model_class.human_attribute_name(:country_code) %>:</strong></dt>
  <dd><%= @page.country_code %></dd>
  <% end %>
  <dt><strong><%= model_class.human_attribute_name(:reference_url) %>:</strong></dt>
  <dd><%= link_to @page.reference_url %></dd>
  <!--
  <dt><strong><%= model_class.human_attribute_name(:reference_url_title) %>:</strong></dt>
  <dd><%= @page.reference_url_title %></dd>
  <dt><strong><%= model_class.human_attribute_name(:reference_url_language) %>:</strong></dt>
  <dd><%= @page.reference_url_language %></dd>
  -->
  <dt><strong><%= model_class.human_attribute_name(:csv_source_url) %>:</strong></dt>
  <dd><%= link_to @page.csv_source_url %></dd>
  <dt><strong><%= model_class.human_attribute_name(:csv_source_language) %>:</strong></dt>
  <dd><%= @page.csv_source_language %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_item_description_en) %>:</strong></dt>
  <dd><%= @page.new_item_description_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_party_description_en) %>:</strong></dt>
  <dd><%= @page.new_party_description_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_party_instance_of_item) %>:</strong></dt>
  <dd><%= link_to_wiki @page.new_party_instance_of_name, @page.new_party_instance_of_item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_district_description_en) %>:</strong></dt>
  <dd><%= @page.new_district_description_en %></dd>
  <dt><strong><%= model_class.human_attribute_name(:new_district_instance_of_item) %>:</strong></dt>
  <dd><%= link_to_wiki @page.new_district_instance_of_name, @page.new_district_instance_of_item %></dd>
  <dt><strong><%= model_class.human_attribute_name(:executive_position) %>:</strong></dt>
  <dd><%= @page.executive_position %></dd>
  <dt><strong><%= model_class.human_attribute_name(:archived) %>:</strong></dt>
  <dd><%= @page.archived %></dd>
  <dt><strong>Statements</strong></dt>
  <dd>Active: <%= @page.statements.where(duplicate: false, removed_from_source: false).count %></dd>
  <dd>Duplicates: <%= @page.statements.where(duplicate: true).count %></dd>
  <dd>Removed from CSV source: <%= @page.statements.where(duplicate: false, removed_from_source: true).count %></dd>
  <dd>Total: <%= @page.statements.count %></dd>
</dl>

<%= link_to t('.back', default: t("helpers.links.back")),
              pages_path, class: 'btn btn-default'  %>
<%= link_to t('.edit', default: t("helpers.links.edit")),
              edit_page_path(@page), class: 'btn btn-default' %>
<%= link_to t('.destroy', default: t("helpers.links.destroy")),
              page_path(@page),
              method: 'delete',
              data: { confirm: t('.confirm', default: t("helpers.links.confirm", default: 'Are you sure?')) },
              class: 'btn btn-danger' %>

<%= link_to 'Load statements', load_page_path(@page), method: :post, class: 'btn btn-default' %>
<%= link_to 'Create or update verification page on Wikidata', create_wikidata_page_path(@page), method: :post, class: 'btn btn-default' %>

<p id="wqs-link-container">
  <a href="https://query.wikidata.org/#<%= ERB::Util.url_encode(@query) %>">Find current positions from Wikidata</a>
</p>