config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  # Admin
  resources :pages do
    member do
      post :load
      post :create_wikidata
    end
  end

  # Frontend
  resources :statements, only: %i[index show] do
    collection do
      get 'statistics'
    end
  end
  resources :verifications, only: %i[create]
  resources :reconciliations, only: %i[create]

  match '/api-proxy' => 'media_wiki_api#api_proxy', :via => %i[get post]

  get 'wikidata-page-setup', to: 'wikidata_page#setup'

  get 'frontend', to: 'general#frontend'
  root 'general#index'
end

app/views/layouts/_flash.html.erb
<%= content_tag(:div, alert, class: 'alert alert-danger', role: 'alert') if alert %>
<%= content_tag(:div, notice, class: 'alert alert-success', role: 'alert') if notice %>

app/views/layouts/_header.html.erb
<%= nav_bar responsive: true do %>
  <%= menu_group do %>
    <%= menu_item "Home", root_path %>
    <%= menu_divider %>
    <%= menu_item "Pages", pages_path %>
    <%= menu_divider %>
    <%= menu_item "Statistics", statistics_statements_path %>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Verification Pages</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/header' if authenticated? %>
    <div class="container">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div>
  </body>
</html>